# Generated by Django 5.0.3 on 2024-03-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fee',
            new_name='age',
        ),
    ]
