# Generated by Django 5.0.3 on 2024-04-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_rename_age_student_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='userId',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
